"""criando tudo(denovo)

Revision ID: f362052d379b
Revises: 
Create Date: 2026-05-07 18:12:50.990827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f362052d379b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salas',
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('anotacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('usuarios',
    sa.Column('id_usu', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_usu'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('alunos',
    sa.Column('id_alu', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('num_chamada', sa.Integer(), nullable=False),
    sa.Column('advertencia', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id_sala'], ),
    sa.PrimaryKeyConstraint('id_alu')
    )
    op.create_table('tarefas',
    sa.Column('id_tarefa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id_sala'], ),
    sa.PrimaryKeyConstraint('id_tarefa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas')
    op.drop_table('alunos')
    op.drop_table('usuarios')
    op.drop_table('salas')
    # ### end Alembic commands ###
